DigitalCommons/land-explorer-front-end

src/components/modals/MyMaps.js, src/components/modals/MySharedMaps.js, src/reducers/MyMapsReducer.js, src/routes/MapApp.js
Closes #102 
Before, a failure to load the maps would logout the user. Now it just displays an error message in the maps section of the app.
The way I tested it was adding a `throw "test error"` line in the try block where the maps endpoint is called. I'm not sure how you'd test it without the maps failing, which they currently don't.
The app no longer logs out the user if the map endpoint fails for some reason. Instead, an error message is displayed in the maps section.
No.
=> Add Graceful Error Handling for Map Load Failure

src/components/Nav.js, src/components/modals/Share/EmailShare.js, src/reducers/ShareReducer.js
Closes #78 
UX for sharing maps was baffling, it didn't do anything when you pressed the button
Test sharing by email. Open a map, then click share in bottom left OR open my maps and click the little arrow in the row with the map name, this is the other way to open map sharing.
There is more to do for sharing maps UX, basically making sure people now that the button SYNCS, so removing people's emails is actually removing their access, not just refraining from adding them again.
nope
=> Sharing Maps UX Makes More Sense

src/assets/styles/_datalayers.scss, src/components/DataGroupLine.js, src/components/DataGroupMarker.js, src/components/DataGroupPolygon.js, src/components/DataGroupPopup.js, src/components/Drawing.js, src/components/MapDataGroups.js, src/components/MapboxMap.js
Closes #121
Polygons and Lines didn't have data group components that would display on the map even if they existed in the data group database.
turn on a data layer that has polygons and lines in. The default test user has such a layer.
Click on the polygons and lines to add them to a map.
- Data Groups can now include polygons and lines which can also be converted to drawn objects on maps.
- Ensure migration and seeding scripts are run
=> Make Polygons and Lines visible when coming from data groups

src/assets/styles/_datalayers.scss, src/components/Markers.js
Adds clustering to drawn markers, so that there's consistency 
1. draw some markers near to each other
2. zoom out to see the clustering
Drawn items cluster like data group items now.
Nope
=> Add clustering to drawn items

src/assets/styles/_datalayers.scss, src/components/NavLandData.js
Closes #134 
Change the icon in the layers section so that it is consistent across the app.
- Open a new map and draw a marker/polygon
- Have a look at the behaviour of the expand button when expanding + collapsing a drawing's info
- Go to the layer panel and expand + collapse a section. The expand icon should look and behave the same.
=> Change expand button to chevron icon

src/components/MapCommunityAssets.js, src/components/MapDataGroups.js, src/components/Markers.js
Closes #144 
When a drawn marker is in a cluster with nearby markers, nothing happens if you click the cluster. The only way to make anything happen is to zoom in enough that the cluster separates, then you can see individual marker popups.
This change makes the map zoom in when clicking a cluster, so that it separates. And it also makes the popup appear from a cluster if that marker is clicked in the info side panel.
1) Draw two or more markers close to each other
2) Zoom out until they cluster.
3) Click the cluster and the map should zoom back in
4) Zoom out again until the cluster.
5) Click a marker on the info side panel. The popup for that marker should appear from the cluster, without zooming in.
6) Then click on the cluster. It should zoom in and the popup should stay open for the …
=> Zoom in when clicking a cluster

src/assets/styles/_datalayers.scss, src/components/DataGroupLine.js, src/components/DataGroupMarker.js, src/components/DataGroupPolygon.js, src/components/DataGroupPopup.js, src/components/Drawing.js, src/components/DrawingLayers.js, src/components/DrawingPopup.js, src/components/MapDataGroups.js, src/components/MapboxMap.js, src/components/MarkerPin.js, src/components/Markers.js, src/components/PolygonSection.js, src/components/common/DrawingTool.js, src/components/common/ToggleSwitch.js, src/reducers/DrawingReducer.js, src/reducers/MarkersReducer.js, src/utils/saveMap.js
Closes #123 
Drawn objects have a description field in the database, which isn't currently visible or editable. This change makes the description editable, using similar UX to #126   
Open a saved map
Click on a marker/polygon/line
Click edit
change text of name/description
press the tick to save
press the cross to cancel
Do the same for a new map that isn't yet saved
Also, test with some layers enabled to make sure clicking between drawn objects and datagroup objects is as expected
Open the info panel and click on a drawn object. Its popup should appear. If the object is part of a cluster, the number should turn to the active 'green' colour to signal that it is within the popup
=> LX-123 Editable Descriptions of Drawn Objects

src/components/MapLayers.js, src/components/MenuKey.js, src/components/NavLandData.js
Closes #170 
Connects to uploaded tilesets on mapbox to provide new overlays showing administrative boundaries
Select the data layers section
scroll to administrative boundaries
toggle the various new layers
Nope
=> Add Admin Boundaries Section to Data Layers

package.json, src/actions/MapActions.js, src/actions/UserActions.js, src/components/MapCommunityAssets.js, src/components/MapProperties.js, src/components/NavCommunityAssets.js, src/components/Navbar.js, src/components/common/MultipleNodal.js, src/components/common/Nodal.js, src/components/modals/EmailShare.js, src/components/modals/MyMaps.js, src/components/modals/MySharedMaps.js, src/components/modals/Save.js, src/components/modals/SaveCopy.js, src/components/modals/SaveSnapshot.js, src/routes/ChangeDetails.js, src/routes/ChangeEmail.js, src/routes/FourOhFour.js, src/routes/MapApp.js, src/routes/MyAccount.js, src/routes/Register.js, src/routes/ResetPassword.js, src/utils/saveMap.js
Closes #178 
In https://github.com/DigitalCommons/land-explorer-back-end/pull/33 I added unit tests and tidied up the docs for the API routes. I removed the trailing slash from some API routes and didn't realise it would make a difference, but the routes stopped working because the front-end API calls still use the trailing slashes.
To be consistent and avoid confusion, we'll just remove all trailing slashes from API routes. Most of the forum threads online recommend this e.g. https://stackoverflow.com/questions/61547014/restful-uri-trailing-slash-or-no-trailing-slash
We also remove trailing slash from links to the homepage '/app', since these are inconsistent and mean the page doesn't load.
- Try saving/deleting a map. These are two of the routes that have been changed. (I've carefully …
=> Remove trailing slashes from API routes

src/actions/DataGroupActions.js, src/actions/MapActions.js, src/actions/UserActions.js, src/actions/common/RequestActions.js, src/components/MenuMain.js, src/components/MenuProfile.js, src/reducers/AuthenticationReducer.js, src/routes/Login.js, src/routes/MapApp.js, src/routes/Register.js, src/routes/ResetPassword.js, src/utils/Auth.js
Closes #194 
When we hit a 401 error on the client side, we now log out and say that the session timed out. The user can then log back in and re-authenticate properly. Previously, the client just stayed logged in but the API calls all silently failed.
1. Login
2. On the server, change the TOKEN_KEY in .env
3. Reload the server with pm2 restart 0
4. Try moving/editing a map, or opening MyMaps on the client. The session should time out and return to the login screen.
Other things to test, since they were refactored:
- manual log out
- logging in with incorrect password
- user registration
=> LX-194 Prompt re-login if we get 401 Unauthorized error

src/components/modals/LinkShare.js, src/reducers/UserReducer.js
Closes #196 
When sharing a GeoJSON link, we currently just display the map's data in our own internal non-standardised format. It doesn't include polygons/lines and also doesn't include datagroup objects.
This change instead outputs proper GeoJSON data that can be imported by other programs, with the same data that we include in the shapefiles.
- Create a map and add some of your own drawings + enable a data group with objects
- Create a GeoJSON public link
- Open the link in a new tab and it should include all the data from your map
Also test creating a snapshot of the map, because some of this code was fixed at the same time (it was broken for new maps that had data groups enabled)
=> LX-196 Improve GeoJSON export

src/assets/styles/_modals.scss
Closes  #203
Fixes misaligned snapshot icon.
Open the my maps modal and check the icon's alignment
=> Added background position propertyto snapshot-icon style

src/reducers/rootReducer.js
Data leak on logout of LX (when logging in the last accessed map would be open, this happened across user accounts when using the same browser).
1. Log into LX
2. Open a map and dialogue if present
3. Logout and login again - the title bar should read `Untitled Map - add title to save map` and default map should be visible
4. Repeat the above switching while between user accounts in the same browser
=> data cleared from redux store on logout

src/actions/LandOwnershipActions.js, src/actions/MapActions.js, src/assets/styles/_buttons.scss, src/assets/styles/_datalayers.scss, src/assets/styles/_left-pane.scss, src/assets/styles/_ownership-search.scss, src/assets/styles/_pagination.scss, src/assets/styles/_properties.scss, src/assets/styles/_variables.scss, src/assets/styles/style.scss, src/components/common/Button.js, src/components/common/Pagination.js, src/components/common/Tooltips.js, src/components/left-pane/LeftPane.js, src/components/left-pane/LeftPaneInfo.js, src/components/left-pane/LeftPaneRelatedProperties.js, src/components/left-pane/PropertySection.js, src/components/left-pane/RelatedProperties.js, src/components/map/MapProperties.js, src/components/map/MapboxMap.js, src/components/map/PropertySearchPoly.js, src/reducers/RelatedPropertiesReducer.js, src/reducers/ShowPropertyPolyReducer.js, src/reducers/rootReducer.js
Closes #256
The ability to search for a proprietor's other properties has been added to the property panel. A button now appears below the property details and above the clear property button.
Once the search has been initiated, the new **Ownership Search** panel opens and if applicable the proprietors other properties are listed.
These can be clicked, taking you to the relevant location on the map.
When a property listing within the **Ownership Search** panel is clicked, you are taken to the relevant highlighted polygon but the highlighting disappears when the **Land Registry** layer rerenders. However, once you interact with the map the highlighted poly reappears.
=> 256 implement fe functions for landreg back search

src/actions/LandOwnershipActions.js, src/components/left-pane/LeftPane.js, src/components/left-pane/PropertySection.js, src/reducers/RelatedPropertiesReducer.js, src/reducers/ShowPropertyPolyReducer.js
Closes #261
Ownership Icon is no longer visible by default, it only appears when an ownership search has been initiated. It disappears when that search has been cleared.
I did initially add conditions relating to zoom level and the ownership layer being visible, but these are unnecessary if a check is made on whether the search is empty or not.
Search is also cleared when the property from which the search was initiated is cleared from the info panel, triggering the icon to disappear.
=> 261 backsearch only show the ownership icon when there is data to display

src/actions/LandOwnershipActions.js, src/components/left-pane/LeftPaneInfo.js, src/components/left-pane/LeftPaneRelatedProperties.js, src/components/left-pane/PropertySection.js, src/components/left-pane/RelatedProperties.js, src/components/left-pane/RelatedPropertySection.js, src/components/map/MapProperties.js, src/components/map/MapboxMap.js, src/components/map/PropertySearchPoly.js, src/reducers/RelatedPropertiesReducer.js, src/reducers/ShowPropertyPolyReducer.js
Closes #263
- open property,
- check ownership
- select multiple
- go to where they are, check they appear on map
no
=> 263 backsearch ownership panel allow selecting multiple properties

src/actions/LandOwnershipActions.js, src/assets/styles/_left-pane.scss, src/assets/styles/_variables.scss, src/components/left-pane/LeftPaneInfo.js, src/components/left-pane/RelatedProperties.js, src/reducers/LandOwnershipReducer.js, src/reducers/RelatedPropertiesReducer.js
Closes #265
add clear all buttons
- property boundaries
- click on some
- notice clear all button appears, click to see if cleared
- add some by checking ownership
- on ownership, activate some
- go back to info, clear all
- go back to ownership, should now be grey again
no
=> add clear all button

src/actions/MapActions.js, src/components/left-pane/DrawingTool.js, src/components/left-pane/LeftPane.js, src/components/map/MapboxMap.js, src/components/modals/NewMap.js, src/index.js, src/pages/Login.js, src/pages/MapApp.js, src/pages/Register.js, src/reducers/DrawingsReducer.js, src/reducers/LeftPaneReducer.js, src/reducers/MapMetaReducer.js
Closes #247
We are not redrawing the polygons properly when switching maps or opening new maps.
This is causing old polygons to linger but not be selectable/editable.
And it means that polygons in the new map throw an error when trying to edit them, since their feature IDs are not registered with mapbox.
I was able to reproduce this on both development and production by following these steps:
1. Draw a polygon
2. Open a map containing a different polygon
3. The first polygon lingers but is not selectable. The other polygon throws an error if you select it then click 'Edit'. (see logs in production since it throws an exception gracefully)
I'm pretty sure this is from all the refactoring work a few months ago (replacing component props with Redux and functionalising the Mapbox component), …
=> LX-247 Fix lingering polygons and featureId exception

src/actions/LandOwnershipActions.js, src/actions/MapActions.js, src/components/left-pane/LeftPaneLandData.js, src/reducers/LandOwnershipReducer.js
Part of #294 
- Save a new map and then toggle the land ownership layer.
- After toggling, the map should autosave (indicated under the map title)
- Refresh the browser, re-open the map and the layer should be displayed according to its previous state
Note that any highlighted properties will be lost. This work is to be completed in the rest of #294
=> Autosave ownership layer display

package.json, src/components/map/MapboxMap.js, yarn.lock
Closes #293
Tapping on drawn polygons and the property boundary layer doesn't work on touch screens.
We're hitting the problem described here https://github.com/mapbox/mapbox-gl-draw/pull/869
The issue was fixed by https://github.com/mapbox/mapbox-gl-draw/pull/1146 in this commit https://github.com/mapbox/mapbox-gl-draw/commit/84e35b7aa308c69a44b483296baa6ac1c6dc9db8
However, they reverted the fix because it broke editing of drawings on mobile https://github.com/mapbox/mapbox-gl-draw/pull/1158
But we don't allow drawings on mobile anyway, so this doesn't matter to us.
So we will use this specific commit of the mapbox-gl-draw repo, and we can wait on a proper fix before we upgrade the package again
- On desktop, save a map with a polygon
- Open this saved map on a mobile device and try to …
=> LX-293 Check out version of mapbox-gl-draw with fix for touch screens

src/actions/MapActions.js, src/components/left-pane/LeftPaneLandData.js, src/components/map/MapboxMap.js, src/pages/MapApp.js
Closes #316
If a browser refresh is performed when a map is open, LX is reloaded with the default untitled map.
As suggested by @rogup, on opening a map the mapId is added to the browser's sessionStorage, and when browser tab is reloaded a check is run and if a mapId is present the requisite map is reloaded.
- Log in to LX
- open a map
- use map
- refresh the browser tab
=> 316 - SFG reload map on refresh

docs/intro.md, scripts/deploy.sh, src/actions/LandOwnershipActions.js, src/components/left-pane/LeftPaneLandData.js, src/components/map-controls/ControlButtons.js, src/components/map/MapPendingProperties.js, src/components/map/MapboxMap.js, src/reducers/LandOwnershipReducer.js, src/reducers/UserReducer.js
- Add UI to allow super users to view pending polygons from the PBS, which have been downloaded from INSPIRE data and are pending analysis.
- Corrections to docs about the property boundaries data
When this is deployed to `main`, it must be deployed alongside the PBS changes in https://github.com/DigitalCommons/property-boundaries-service/pull/15 and LX BE changes in https://github.com/DigitalCommons/land-explorer-back-end/pull/60 to ensure compatibility
=> INSPIRE pipeline: Allow super users to view pending polygons

src/components/left-pane/RelatedProperties.js
Currently, when an arrow next to a property within the 'Ownership Search' panel is clicked, the property is not highlighted in red on the map.
Closes #311
After investigation the `handlePropertyClick` function only needed to be be added to the `gotoProperty` function within `RelatedProperties.js`.
I was unable to reproduce the second bug mentioned in issue #311 locally, on staging or on live (click 'clear all' within the 'Ownership Search' panel, click another property within this panel and all properties listed in the panel are highlighted green).
1. Turn on ownership search
2. Zoom in and click on a green poly
3. Open the 'Land Information' panel and click 'Check for other properties'
4. Click an arrow to the right of a property within the 'Ownership Search' panel
=> Ownership Search - highlighting fix for selected properties

src/actions/MapActions.js, src/components/map-controls/ControlButtons.js, src/components/map/MapPendingProperties.js, src/components/map/MapProperties.js, src/components/map/MapboxMap.js, src/reducers/MapReducer.js
Related to https://github.com/DigitalCommons/property-boundaries-service/issues/16
If a user enables the property boundaries layer from the initial zoomed out map, then clicks the 'zoom to properties' button, the API request gets fired before zooming in. This means it queries ALL the property data, causing an OOME. I managed to reliably repro this and see the heap size start increasing exactly when I did the above. I also took a node memory snapshot using https://nodejs.org/api/cli.html#--heapsnapshot-near-heap-limitmax_count, and saw over 100K properties in a huge array in the memory, confirming the above.
I'm not sure why this hasn't been an issue before tbh. The only thing I can think of right now is that since I updated some of the npm dependencies recently, maybe there has been an …
=> Query properties after zoom has ended
