DigitalCommons/land-explorer-front-end

src/components/modals/Share/EmailShare.js

Closes #77
include the id 
open a map
on the left click share
share by email
enter email
press +
press enter
none

Fix email id sharing

---

src/routes/Register.js

Closes #87 
add some styles so that scrolling is enabled
visit registration page, use screen shorter than 800px.
registration on small screen
nothing new

change style of main div on register page

---

src/assets/styles/_datalayers.scss
src/assets/styles/_tooltips.scss
src/components/MapDataGroups.js
src/components/modals/Save.js
src/routes/Register.js

Closes #89
So people can add data group markers to their own maps.
Turn on a data group
click on a marker
click save icon in bottom right of pop-up
select map to save to
press save
map should have the marker in
Make sure the item types table exists on the database before deploying

Save data group marker to map

---

package.json
src/components/Drawing.js
src/components/DrawingLayers.js
src/components/MapboxMap.js
src/components/MarkerPin.js
src/components/MarkerSection.js
src/components/Markers.js
src/components/PolygonSection.js
src/components/modals/Save.js
src/data/dummyDataGroups.js
src/reducers/DrawingReducer.js
src/reducers/MapMetaReducer.js
src/reducers/MapReducer.js
src/reducers/MarkersReducer.js
src/routes/MapApp.js
yarn.lock

Closes #81 #90 #91 #92 #101
The markers, polygons and lines are currently stored within the stringified JSON that is stored in the 'data' column of the map table in the DB. When there are too many drawings (in the order of 1000) this string overloads and the map cannot be saved. Having drawings in the DB will also make it easier to allow multiple people to work on the same map in the future (although this isn't supported yet).
The solution to this is to create markers, polygons, and lines tables in the DB. There will also be a map_memberships table that, for any saved map id will contain the approriate references to drawings on this map.
Create some markers, lines and polygons and save the map.
Repeat this for another map.
Edit, remove and make new drawings on each map.
Edit a map and …

Map memberships

---

src/components/MapDataGroups.js

Closes #89
This loads the map when the marker has been saved, so you can see that it exists.
Create a new map
Turn on a data layer
Click on a data marker
Click save to map (save icon in bottom right)
Select map
Select save
added
Ensure migrations and seeds are up to date on back end.

Load the map when saving shared data to a map

---

src/components/DataGroupMarker.js
src/components/DataGroupPopup.js

makes #126 easier
no test
nothing visible, consoldiates component reuse
none

data group marker uses data group popup

---

src/assets/img/icon-add.svg
src/assets/img/icon-cross.svg
src/assets/img/icon-pencil.svg
src/assets/img/icon-tick.svg
src/assets/styles/_datalayers.scss
src/components/DataGroupPopup.js

Closes #126 
Need to be able to 
- Turn on a data layer
- Click on a marker/polygon/line
- Click plus to save to map
- Click edit to edit
- change text
- press the tick to save
- press the cross to cancel
none

Add Editing Data Group Markers, Polygons and Lines

---

src/reducers/NavigationReducer.js

Closes #133 
Many users fail to find the LX functionality within the cog menu.
Let's just have this open by default.
- Visit LX
- Check that cog menu starts as Open
- Check that it can be closed and reopened in the same way as now

Set cog menu to open by default

---

src/components/NavLandOwnership.js

135 remove ecommerce

---

src/components/MenuMain.js

Closes #166 which is a bug fix
Open top right burger menu, click community, get taken to community section of static site
nope

Fix link in burger menu

---

src/assets/styles/_nav.scss
src/components/NavDrawingTray.js
src/components/NavLandData.js
src/components/NavTray.js

Closes #165
Add an optional header to the nav tray component.
Created a header with link in the land data section
Open the land data section, look at the top below the title
Added a link where people can add their own data to Land Explorer
None

add header prop, create description in nav land data

---

src/components/Drawing.js

Closes #180
Removed an on click method on the marker that was keeping the popup open. 
Draw polygon, click on it, click on the x to close it
none

Bug fix: Close button on polygons should close the popup

---

src/assets/styles/style.scss
src/components/MapName.js
src/components/MapboxMap.js
src/components/Navbar.js
src/reducers/MapReducer.js

Closes #173 
We want to edit the map name, so 
Load the page, the title at the top should say Untitled Document
Click on the title to make it editable
Add a new title
Click off the title to change the name of the map
Note, you still need to manually save for the name change to take effect in the database.
None

Make map names editable

---

src/components/MapDataGroups.js
src/components/MapboxMap.js
src/components/Markers.js

Closes #153 
Moved the data group markers generation to the drawn markers component
Turn on a data group with markers in, draw a marker next to a data group marker, watch the cluster form.
None

Group drawn and data group markers together in the same clusters

---

src/actions/LandOwnershipActions.js
src/actions/MapActions.js
src/components/left-pane/LeftPaneInfo.js
src/components/left-pane/PropertySection.js
src/components/map/MapProperties.js
src/reducers/LandOwnershipReducer.js

Closes #215 
If you click a land registry polygon, it adds the property to your map and highlights it in red. But you can click the same property again and it will add an unwanted duplicate, highlighting it again and again so it becomes darker red. The overall behaviour is also clunky. It's difficult to understand which piece of land registry info corresponds to which polygon, once they've been added.
Results of these changes:
- the same property can only be added once to a map
- clicking on a property clearly indicates that it has been selected, by highlighting it in a darker red, and expanding its corresponding data in the info pane
1. Zoom in and enable the land registry layer
2. Click on a property so that it gets highlighted and added to the info pane
3. Move the map and click on the …

LX-215 Fix property polygons UI

---

package.json
src/assets/styles/_forms.scss
src/assets/styles/_top-bar.scss
src/components/top-bar/MapTitleBar.js
src/components/top-bar/SearchBar.js
src/components/top-bar/TopBar.js
yarn.lock

Closes #222 
Search bar behaves badly when updating and deleting text. It collapses inappropriately making it really hard to use.
In these changes, we fix the search bar so that
- on a big screen:
- it stays expanded. It only collapses if there is no text in it and it is not in focus.
- on a small screen (e.g. on mobile):
- it expands across a large part of the top bar and hides the map name, so that there is room to see what you're typing
- it collapses if it loses focus, even if there is text currently in it, to make room for the map name
- Play around with the search bar on both desktop and mobile to check the above spec is working

LX-222 Fix search bar expansion

---

src/components/map/MapboxMap.js

Closes #215
onZoom contained a closure, so it wasn't updating the actual zoom figure from the map
- test land reg layer
-

change how zoom is set from map

---

src/components/common/Tooltips.js
src/components/left-pane/LeftPane.js
src/components/top-bar/MenuMain.js
src/components/top-bar/MenuProfile.js
src/components/top-bar/ProfilePic.js
src/hooks/useClickOutside.js
src/pages/Login.js

Closes #236 
Addresses minor bugs discover in spike #231
- Check for overlapping of the left pane and profile menu on mobile
- Check for persistent tool tip on mobile while opening and closing the left pane by tool icons
- When logged out check that the main menu closes during navigation.

236 lx improve menus on mobile

---

src/components/map/MapboxMap.js

Closes #238
Pinch zoom currently inactive on mobile, updated `touchZoomRotate` to true to hopefully rectify this.
Test pinch zoom on handheld devices

touchZoomRotate setting set to true

---

src/components/map/MapProperties.js

Closes #59
The boundary service data comes through slightly different (lat,lng reversed) and no need for json parsing.
- check boundary service works
Front End Changes for Boundary Service
none

Front End Changes for Boundary Service

---

src/components/left-pane/LeftPaneLandData.js

Closes #266
The 'Land Registry' layer name changed to 'Property Boundaries'

name updated to Property Boundaries

---

src/pages/Register.js

Closes #270 
Registration, check terms of use is there
no

add terms of use to sign up

---

src/assets/styles/_properties.scss
src/components/left-pane/LeftPaneRelatedProperties.js

Closes #250
add the license
Open up related properties, scroll down, there's the license 
no

add license info the related properties

---

src/components/left-pane/PropertySection.js

Closes #267
Add license to info panel
Turn on properties, click on one, note the license
no

add the license

---

src/assets/img/icon-goto.svg
src/assets/styles/_ownership-search.scss
src/components/left-pane/RelatedProperties.js

Closes #262
Adds icon for traveling to property.
- open a property that has info
- check for other properties
- note the arrow, click on it to see if it takes you to the right place
no

add icon and functionality

---

src/components/left-pane/LeftPaneRelatedProperties.js

Closes #264 
- Try selecting all the properties of big landowners (e.g. the National Trust, the Queen)
- Check that they are all selected as expected and that the website doesn't crash

LX-264 Add ownership select all button

---

src/components/modals/Modals.js
src/components/modals/MyMaps.js
src/components/modals/MySharedMaps.js
src/components/top-bar/MenuProfile.js
src/reducers/ModalReducer.js

Update user menu, remove superfluous links, update donate URL.
- Check the donate link directs to:  https://opencollective.com/digitalcommonscoop
- Check the My Maps link open the same modal as 'Open' on the map menu

updates as per issue

---

config/webpack.config.common.js

Relates to Umami changing where the tracking script comes from
- Visit some pages, have a look that umami shows what you're looking at
Update umami analytics script to new instance
No

Update umami analytics script to new instance
